version: "3"

services:
  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - mongodb:/data/db

  redis:
    image: redis:latest

  frontend:
    build:
      context: ./my-react-app
      dockerfile: Dockerfile
    ports:
      - "5173:5173"

  backend:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports: 
      - "4000:4000"
    environment:
      PORT: 4000
      DB_URL: mongodb://mongodb:27017
      REDIS_CONNECTION_URL: redis://redis:6379
      REDIRECT_URI: http://localhost:5173/callback
      SPOTIFY_CLIENT_ID: "48b7db8544514f8881e4f3617000235f"
      SPOTIFY_CLIENT_SECRET: "b75176af1c9f44489dcc858a539b2082"
    depends_on:
      - mongodb
      - redis

volumes:
  mongodb: {}