version: "3"

services:
  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - mongodb:/data/db

  redis:
    image: redis:latest

  backend:
    build: .
    ports: 
      - "4000:4000"
    environment:
      PORT: 4000
      DB_URL: mongodb://mongodb:27017
      REDIS_CONNECTION_URL: redis://redis:6379
    depends_on:
      - mongodb
      - redis

volumes:
  mongodb: {}